# Generated by Django 4.2.4 on 2023-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dffffcdcde', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
